### ISSUE TITLE
Neutron - E2E Integration

### ISSUE THREAD

**Issue by pragyanshrestha-ibriz** [icon-project/IBC-Integration#536]

**Comment by redlarva** [comment]
Some of the Cosmos SDK commands appear to be broken on the neutron node. Our e2e test framework is heavily dependent on the interchaintest framework, and several commands used by the interchaintest framework are causing errors while conducting e2e tests, so we might need to consider an alternative strategy to testing e2e with neutron. 

https://discord.com/channels/986573321023942708/1029032555405651998/1133366991189717102
```
Albert — Yesterday at 5:40 PM
Neutron is consumer chain, gentx command is not working. You can use neutrond add-consumer-section  instead. And also I'd recommend you to build neutron with make install-test-binary  if you want to run it standalone.
```
