### ISSUE TITLE
Suggestion for Release Workflow 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/IBC-Integration#728]
Raising this issue as a suggestion for the release workflow that would combine a number of steps into one and change the flow by using release-please instead of a number of other actions that I see being used. I use it in the tracker and personal projects where it does the following:

- Takes each conventional commit messages and parses them for prefixes 
- Assigns certain prefixes such as feat / fix to incrementing the semantic version 
- Each time a feat / fix tag is seen it raises a PR which upon merge it will then trigger a release
- Manages a changelog file and the release message for you along with updating the version within your code 

To be clear, the workflows you have are very comprehensive and I didn't come here to raise an issue because of them. Instead I was going to suggest this for goloop since it is missing changelogs + compiled binaries as artifacts but was told by Cyrus that I should instead raise this issue here. So this message is less for this repo (seems like you already have this stuff) and more broadly for things like goloop which could benefit from this and also be potentially towards some standard across the ecosystem. 

- A good example of seeing how this works is in my tool tackle here -> https://github.com/sudoblockio/tackle/blob/main/.github/workflows/release.yml#L16
- The changelog types can be customized to your needs and flow into release notes as seen here -> https://github.com/sudoblockio/tackle/releases so things like a custom prefix (Ex. commit message `contract: do someting`) could then flow into the release notes. 
- Changelog looks like this -> https://github.com/sudoblockio/tackle/blob/main/CHANGELOG.md and the version gets updated through On merging the PR created by the action an automated commit will update your code as seen here -> https://github.com/sudoblockio/tackle/blob/main/tackle/__init__.py#L2 
- PR looks like this -> https://github.com/sudoblockio/icon-tracker-frontend/pull/297

I use this action in every repo and happy to assist if this is something that you want.

**Comment by FezBox** [comment]
@pragyanshrestha-ibriz is there a reason this is in the icebox?

**Comment by DeepakBomjan** [comment]
Hi @robcxyz I tried using the above action, but it doesn't work as expected in projects like IBC-integration, which involve multiple languages. Right now, this action only supports single-language projects. We will be checking more options to optimize the release action of this project. 

Furthermore, there is still difficulty in specifying the release version, given that there are multiple components (contracts) each with its own version. Hence, having a single repository-level release version seems to cause confusion regarding the actual version of the artifact. Please suggest any ideas you may have on this matter, or if there are similar projects on GitHub.
