### ISSUE TITLE
Lightclient translation

### ISSUE THREAD

**Issue by pragyanshrestha-ibriz** [icon-project/IBC-Integration#761]

**Comment by ibrizsabin** [comment]
https://github.com/icon-project/IBC-Integration/pull/754

**Comment by pragyanshrestha-ibriz** [comment]
On hold due to blocker due to changes on the lightclient and sdk version on Centauri chain.
Prioritization currently on centralized relay and Injective deployment.
Will continue work on next sprint as well.

**Comment by pragyanshrestha-ibriz** [comment]
On hold due to blocker due to changes on the lightclient and sdk version on Centauri chain.
Prioritization currently on centralized relay and Injective deployment.
Will continue work on next sprint as well.

**Comment by ibrizsabin** [comment]
future changes will be tracked here [786](https://github.com/icon-project/IBC-Integration/issues/786)
