### ISSUE TITLE
error following e2e setup tutorial

### ISSUE THREAD

**Issue by FidelVe** [icon-project/IBC-Integration#773]
following the e2e setup tutorial in this link https://github.com/icon-project/IBC-Integration/blob/main/docs/e2e-integration-test-setup.md

When executing step 2 of "Setting up the environment" Im getting the following error:
```
$ make build-builder-img
make: *** No rule to make target 'build-builder-img'.  Stop.
```
The `Makefile` of the `ibc-relay` repo doesnt have a `build-builder-img` command
https://github.com/icon-project/ibc-relay/blob/main/Makefile

**Comment by AntonAndell** [comment]
Step two again referes to the IBC-Integrations repo, mabey that should be clearer.
