### ISSUE TITLE
Improvements for the e2e-integration-test-setup tutorial.

### ISSUE THREAD

**Issue by FidelVe** [icon-project/IBC-Integration#775]
Hello team.

The following is a list of issues encountered while trying to execute the steps in the `e2e-integration-test-setup` tutorial.

* The tutorial doesnt explicitly indicates at the beginning of the document to clone the `https://github.com/icon-project/IBC-Integration` repo.
* Since is required to clone and install many different repositories (IBC-Integration, ibc-relay, goloop, etc) It would be better to recommend the user to create a root folder (ie. tell the user to create a folder named `ibc-e2e-tests`) and inside this root folder indicate during the progression of the tutorial to clone and install all the required repos in this folder.
* After cloning the `ibc-relay` repo there is no explicit indication to go into the `IBC-Integration` folder and execute the `make build-builder-img` command.
* Are the steps labeled as `Additional steps for Apple Silicon` required also for linux users? should linux users bypass these steps?
* At the end of the `Additional steps for Apple Silicon` there is a note indicating *"Change the image name and version of Archway/Neutron in e2e-config.yaml or e2e-config-neutron.yaml"*, where are these files? and how can the user find the image name and version of Archway/Neutron?
* On the section *"Running IBC Integration System Tests"* the first step labeled as *"Configure Environment variables"* has the following instructions:
    - `export E2E_CONFIG_PATH=/home/User/IBC-integration/sample-config-archway.yaml`. The `IBC-Integration` folder doesnt have a `sample-config-archway.yml` file, where should we find this file? or this file suppose to be created by the user?
    - `export GOLOOP_IMAGE_ENV=goloop-icon`. what command can the user execute find the goloop image name?
    - `export GOLOOP_IMAGE_TAG_ENV=latest`. what command can the user execute to find the goloop image tag?

* On step 2 labeled *"Run the test script"*. is not explicitly defined to run this command inside the `IBC-Integration` folder.
* As in the previous item the rest of the steps in the tutorial are not explicitly defined to be executed inside the `IBC-Integration` folder.

As a sidenote, I personally couldnt finish the steps in the tutorial I was stuck trying to find correct yaml configuration file to use.

**Comment by pragyanshrestha-ibriz** [comment]
@FidelVe has this issue been resolved now for you?

**Comment by FidelVe** [comment]
The latest comment I left regarding this subject is here

https://github.com/icon-project/IBC-Integration/pull/778#issuecomment-1790790255

I dont know if any new revision has been made to the doc to address the issues I was having.
